version: "3.8"

services:
  backend:
    build:
      context: .  # `emory/` をコンテキストとして指定
      dockerfile: backend/Dockerfile  # backend/ の Dockerfile を参照
    container_name: flask_app
    env_file:
      - config.env  
    environment:
      PYTHONPATH: "/emory/"  # ✅ backend を Python モジュールとして認識
    depends_on:
      - mysql
    volumes:
      - .:/emory  # ✅ ルートディレクトリを `/emory` としてマウント
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    command: ["sh", "-c", "sleep 5 && python backend/run.py"]

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - ./config.env
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
