version: "3.8"

services:
  backend:
    build:
      context: .  # emory/ をコンテキストとして指定
      dockerfile: backend/Dockerfile
    container_name: flask_app
    env_file:
      - config.env  
    environment:
      - PYTHONPATH=/emory  # ✅ backend を Python モジュールとして認識
    depends_on:
      - mysql
      - mysql_test  # ✅ テスト用 MySQL に依存
    volumes:
      - .:/emory  # ✅ ルートディレクトリを /emory としてマウント
    command: ["sh", "-c", "sleep 10 && python backend/run.py"]
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - ./config.env
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD_development}"
      MYSQL_DATABASE: "${DB_NAME_development}"
      MYSQL_USER: "${DB_USER_development}"
      MYSQL_PASSWORD: "${DB_PASSWORD_development}"
    ports:
      - "${DB_PORT_development}:${DB_PORT_development}"
    volumes:
      - mysqldata:/var/lib/mysql

  mysql_test:
    image: mysql:8.0
    container_name: mysql_test_db
    restart: always
    env_file:
      - ./config.env
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD_test}"
      MYSQL_DATABASE: "${DB_NAME_test}"
      MYSQL_USER: "${DB_USER_test}"
      MYSQL_PASSWORD: "${DB_PASSWORD_test}"
    ports:
      - "${DB_PORT_test}:${DB_PORT_test}"
    volumes:
      - mysqldata_test:/var/lib/mysql

  frontend:
    build:
      context: ./frontend  # React アプリのルートディレクトリを指定
    container_name: react_app
    env_file:
      - config.env  # config.env で環境変数を読み込む
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}  # config.env から API URL を設定
      - REACT_APP_PORT=${REACT_APP_PORT}        # React アプリのポートを設定
    ports:
      - "${REACT_APP_PORT}:${REACT_APP_PORT}"   # React アプリのポートを公開
    volumes:
      - ./frontend:/app  # ローカルディレクトリをコンテナ内にマウント
    working_dir: /app
    command: ["npm", "start"]  # React アプリを起動

  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb_local
    ports:
      - "${DYNAMODB_LOCAL_PORT}:${DYNAMODB_LOCAL_PORT}"  # DynamoDB Local のポートを環境変数から取得
    environment:
      - DB_PATH=/home/dynamodblocal/data
    volumes:
      - dynamodb-local-data:/home/dynamodblocal/data  # データの永続化
    command: ["-jar", "DynamoDBLocal.jar", "-inMemory", "-sharedDb"]  # インメモリモードで起動

  
volumes:
  mysqldata:
  mysqldata_test:
  dynamodb-local-data: 
